// Real production domain, confirmed against the Google Business Profile
// listing (which lists it without "www" and over http; https + no-www is
// enforced here as the canonical form). Used for canonical URLs, Open
// Graph/Twitter tags, JSON-LD @id/url fields, and the sitemap generated by
// scripts/prerender.ts. Keep public/robots.txt's Sitemap: line in sync.
export const SITE_URL = 'https://visalatchimanufacturing.com';

export const SITE_NAME = 'Visalatchi Manufactures';

// Shared logo/OG-image source. Single source of truth so Seo.tsx (runtime),
// prerender.ts (build-time head tags) and schema.ts (JSON-LD) can't drift.
export const LOGO_URL =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuC9R9jkHfIHpp-rHGWas-XTdRDmh736cpbPfz2aYBNi3y0OGwLt4nC7943ZKj_5jabLeXo_u72kooxrDZEDFzdlnFnsEAzpN-kRrzFtaKw-Y-dp_ouTJ1_xWqMLl_qlnT3i3b9lDIZK-m2nnK-cPKFfYF89wMqc6R5F8uA3gqa35SgL-OdtFSvSLWPHUI61FNgVB_MOSttS_ktB7jy1_nxPoHa2rNxHxvcZrWOsKRPiFxTAhXTxaLUY';

export const PLANT_ADDRESS = {
  streetAddress: 'No 10/4B Village Street, Sadayan Kuppam Pattai, Thiruvottiyur',
  addressLocality: 'Chennai',
  addressRegion: 'Tamil Nadu',
  postalCode: '600019',
  addressCountry: 'IN',
};

// One human-readable address string, built from PLANT_ADDRESS so the plant
// address used in the Footer's map link, the Footer's map embed, and the
// ContactView map embed can never drift apart into three slightly different
// strings (which is exactly the kind of NAP inconsistency that hurts local
// SEO trust).
export const PLANT_ADDRESS_FULL = `${PLANT_ADDRESS.streetAddress}, ${PLANT_ADDRESS.addressLocality} ${PLANT_ADDRESS.postalCode}, ${PLANT_ADDRESS.addressRegion}, India`;

// Exact coordinates of the verified Google Business Profile pin (resolved
// from https://maps.app.goo.gl/F9VCUnqTkmb3cx568), not a geocoded guess from
// the address text. Used for the map embeds and the LocalBusiness schema's
// geo field, both more accurate signals than an address string lookup.
export const PLANT_COORDS = { lat: 13.1663165, lng: 80.3008765 };

// The actual GBP share link. Used for "Get directions" links instead of a
// constructed maps search URL, since this is the literal link Google
// generated for the verified listing.
export const PLANT_MAPS_SHARE_URL = 'https://maps.app.goo.gl/F9VCUnqTkmb3cx568';

export const PLANT_MAPS_EMBED_SRC = `https://www.google.com/maps?q=${PLANT_COORDS.lat},${PLANT_COORDS.lng}&z=17&output=embed`;

// City-level courier dispatch coverage across Tamil Nadu. Framed as "we
// dispatch to" (true, pan-India courier network), not "we are near you" or
// "we operate a branch in" (which would be false for a single-plant
// business). City-level only, no neighborhoods or industrial estates as
// separate entries, per Google's June 2025 guidance against state/country
// level service areas and to avoid the doorway-page pattern.
//
// IMPORTANT: the current 4 (Chennai, Madurai, Coimbatore, Tiruchirappalli)
// are what GBP's own "Service area" field declares as of 2026-08-13. The
// remaining 8 below are added here because they're truthfully served by the
// existing pan-India courier network, but GBP itself has NOT been updated
// to match yet — update GBP's service area to include them too, so this
// list and the live GBP listing stay in sync (mismatched NAP/service-area
// data across platforms is a real local-SEO trust penalty).
export const TAMIL_NADU_CITIES = [
  'Chennai',
  'Madurai',
  'Coimbatore',
  'Tiruchirappalli',
  'Salem',
  'Tirunelveli',
  'Erode',
  'Vellore',
  'Thoothukudi',
  'Thanjavur',
  'Tiruppur',
  'Karur',
];

// Neighborhoods near the Thiruvottiyur plant — real local-relevance signal,
// not a claim of separate physical branches.
export const CHENNAI_LOCALITIES = [
  'Thiruvottiyur',
  'Tondiarpet',
  'Madhavaram',
  'Perambur',
  'Ambattur',
  'Red Hills',
];

// Full North Chennai neighborhood set (the plant's own zone, Thiruvottiyur).
// Used only as genuine on-page content (ContactView's coverage section) —
// deliberately NOT duplicated into JSON-LD schema or repeated on every page,
// since a business claiming 46 distinct areasServed via structured data
// reads as doorway-page/geo-spam to Google rather than a real service radius.
export const NORTH_CHENNAI_AREAS = [
  'Anna Nagar',
  'Basin Bridge',
  'Broadway',
  'Ennore',
  'Erukanchery',
  'George Town',
  'ICF Colony',
  'Jamalia',
  'Kathirvedu',
  'Kathivakkam',
  'Kodungaiyur',
  'Korukkupet',
  'Kosapet',
  'Lakshmipuram',
  'Madhavaram',
  'Madhavaram Milk Colony',
  'M.K.B. Nagar',
  'Manali',
  'Manali New Town',
  'Manjambakkam',
  'Mannadi',
  'Mathur',
  'Minjur',
  'Moolakadai',
  'Naravarikuppam',
  'New Washermenpet',
  'Old Washermenpet',
  'Otteri',
  'Park Town',
  "Parry's Corner",
  'Pattalam',
  'Perambur',
  'Periamet',
  'Ponniammanmedu',
  'Pulianthope',
  'Puzhal',
  'Red Hills',
  'Royapuram',
  'Selavoyal',
  'Sembiam',
  'Surapet',
  'T.V.K. Nagar',
  'Tiruvottiyur',
  'Tondiarpet',
  'Vallalar Nagar',
  'Villivakkam',
  'Vyasarpadi',
];
