// Real production domain, confirmed against the Google Business Profile
// listing (which lists it without "www" and over http; https + no-www is
// enforced here as the canonical form). Used for canonical URLs, Open
// Graph/Twitter tags, JSON-LD @id/url fields, and the sitemap generated by
// scripts/prerender.ts. Keep public/robots.txt's Sitemap: line in sync.
export const SITE_URL = 'https://visalatchimanufacturing.com';

export const SITE_NAME = 'Visalatchi Manufactures';

// Shared logo/OG-image source. Single source of truth so Seo.tsx (runtime),
// prerender.ts (build-time head tags) and schema.ts (JSON-LD) can't drift.
export const LOGO_URL =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuC9R9jkHfIHpp-rHGWas-XTdRDmh736cpbPfz2aYBNi3y0OGwLt4nC7943ZKj_5jabLeXo_u72kooxrDZEDFzdlnFnsEAzpN-kRrzFtaKw-Y-dp_ouTJ1_xWqMLl_qlnT3i3b9lDIZK-m2nnK-cPKFfYF89wMqc6R5F8uA3gqa35SgL-OdtFSvSLWPHUI61FNgVB_MOSttS_ktB7jy1_nxPoHa2rNxHxvcZrWOsKRPiFxTAhXTxaLUY';

export const PLANT_ADDRESS = {
  streetAddress: 'No 10/4B Village Street, Sadayan Kuppam Pattai, Thiruvottiyur',
  addressLocality: 'Chennai',
  addressRegion: 'Tamil Nadu',
  postalCode: '600019',
  addressCountry: 'IN',
};

// Kept identical to the "Service area" list declared on the Google Business
// Profile listing. Deliberately not a longer wishlist of cities: mismatched
// service areas across the site and GBP read as an inconsistent NAP signal,
// which hurts local trust more than a longer list would help.
export const TAMIL_NADU_CITIES = ['Chennai', 'Madurai', 'Coimbatore', 'Tiruchirappalli'];

// Neighborhoods near the Thiruvottiyur plant — real local-relevance signal,
// not a claim of separate physical branches.
export const CHENNAI_LOCALITIES = [
  'Thiruvottiyur',
  'Tondiarpet',
  'Madhavaram',
  'Perambur',
  'Ambattur',
  'Red Hills',
];

// Full North Chennai neighborhood set (the plant's own zone, Thiruvottiyur).
// Used only as genuine on-page content (ContactView's coverage section) —
// deliberately NOT duplicated into JSON-LD schema or repeated on every page,
// since a business claiming 46 distinct areasServed via structured data
// reads as doorway-page/geo-spam to Google rather than a real service radius.
export const NORTH_CHENNAI_AREAS = [
  'Anna Nagar',
  'Basin Bridge',
  'Broadway',
  'Ennore',
  'Erukanchery',
  'George Town',
  'ICF Colony',
  'Jamalia',
  'Kathirvedu',
  'Kathivakkam',
  'Kodungaiyur',
  'Korukkupet',
  'Kosapet',
  'Lakshmipuram',
  'Madhavaram',
  'Madhavaram Milk Colony',
  'M.K.B. Nagar',
  'Manali',
  'Manali New Town',
  'Manjambakkam',
  'Mannadi',
  'Mathur',
  'Minjur',
  'Moolakadai',
  'Naravarikuppam',
  'New Washermenpet',
  'Old Washermenpet',
  'Otteri',
  'Park Town',
  "Parry's Corner",
  'Pattalam',
  'Perambur',
  'Periamet',
  'Ponniammanmedu',
  'Pulianthope',
  'Puzhal',
  'Red Hills',
  'Royapuram',
  'Selavoyal',
  'Sembiam',
  'Surapet',
  'T.V.K. Nagar',
  'Tiruvottiyur',
  'Tondiarpet',
  'Vallalar Nagar',
  'Villivakkam',
  'Vyasarpadi',
];
